version: 2.1

jobs:
  run-tests:
    working_directory: ~/repo
    docker:
      - image: cimg/node:12.22.7 # Primary execution image
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm ci
      - run:
          name: Run tests
          command: npm run test:ci
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish-npm:
    working_directory: ~/repo
    docker:
      - image: cimg/node:12.22.7 # Primary execution image
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with NPM
          command: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run:
          name: Publish package
          command: |
            # Publish as beta for pre-release tags like v1.2.3-pre.1
            [[ $CIRCLE_TAG =~ ^v.*- ]] && NPM_TAG=--tag=beta
            npm publish $NPM_TAG

workflows:
  version: 2
  test-and-publish:
    jobs:
      - run-tests:
          context:
            - particle-ci-private
          # run tests for all branches and tags
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - publish-npm:
          requires:
            - run-tests
          context:
            - particle-ci-private
          # publish for tags only
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
